kind: pipeline
name: default

steps:
- name: test
  image: maven:3-jdk-10
  commands:
  - mvn clean surefire-report:report

- name: package
  image: maven:3-jdk-10
  commands:
  - mvn package -Dmaven.test.skip=true

- name: ls
  image: bash
  commands:
  - ls -R

- name: notify
  image: drillster/drone-email
  settings:
    host: mail.keremyaldiz.com
    username:
      from_secret: username
    password:
      from_secret: password
    from: admin@keremyaldiz.com
    receipents: [ contact@keremyaldiz.com ]
    subject: Dummy
    body: Dummy
    attachment: target/surefire-reports/\*.xml