kind: pipeline
name: default

steps:
- name: test
  image: maven:3-jdk-10
  commands:
  - mvn clean surefire-report:report

- name: package
  image: maven:3-jdk-10
  commands:
  - mvn package -Dmaven.test.skip=true